---
- hosts: prod
  tasks:
    - name: get file
      block: 
        - get_url:
            url: "http://ketanvj4c.mylabserver.com/index.html"
            dest: "/tmp/index_file"
      rescue: 
        - debug: msg="The file does not exist!"
      always:
        - debug: msg="inside always"
