---
- hosts: prod
  tasks: 
    - name: get files from all hosts
      get_url: 
        url: "http://{{item}}/index.html"
        dest: "/tmp/{{item}}"
      ignore_errors: yes
      with_items:
        - slave1
        - slave2
        - slave3
