--- # having a command post ignore error lets see what happnes ignoreerrortocontinueexec.yml
- hosts: prod
  tasks:
  - name: install Red Hat
    yum:
      name: httpd
      state: latest
    ignore_errors: yes
  - name: create testredhat
    file:
      path: /home/ubuntu/redhatsample.txt
      state: touch
    
  - name: install Debian
    apt:
      name: apache2
      state: latest
    ignore_errors: yes	
  - name: create testdeb
    file:
      path: /home/ubuntu/debiansample.txt
      state: touch
