- hosts: slave2
  become: yes
  tasks:
    - name: install apache
      apt:
        name: apache2
    - name: start and enable apache
      service:
        name: apache2
        state: started
        enabled: yes
    - name: create index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Hello World1!</h1>"
    - name: add 2 line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Hello World1!</h1>"
    - name: add 2 line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h2>Hello World1!</h2>"

