
--- # varinplaybookandmagicvar.yml
- hosts: prod
  vars:
    inv_list: /home/ubuntu/invlist.txt
  tasks:
  - name: Create a new file
    file: 
      path: "{{ inv_list }}"
      state: touch
  - name: copy hosts
    lineinfile: 
      path: "{{ inv_list }}"
      line: "{{ groups['prod'] }}"

