--- # Testing how variables work in vars section of playbook, gather no
- hosts: '{{ myhosts }}'
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: slave1
    gather: no
    package: apache2

  tasks:
  - name: Install the package '{{ package }}'
    apt:
      name: '{{ package }}'
      state: absent
