
--- # Testing how variables work in vars section of playbook
- hosts: '{{ myhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: slave1
    gather: yes
    package: apache2
  
  tasks:
  - name: Install the package '{{ package }}'
    apt: 
      name: '{{ package }}'
      state: present

