--- # Testing how variables work in vars section of playbook, passing var command line
- hosts: '{{ myhosts }}'
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'

  tasks:
  - name: Install the package '{{ package }}'
    apt:
      name: '{{ package }}'
      state: present
