- hosts: slave1
  become: yes
  handlers: 
    - name: restart apache
      service:
        name: apache2
        state: restarted
      listen: "restart webserver"
  tasks: 
    - name: change configuration
      replace:
        path: /etc/httpd/conf/httpd.conf-- need to undertand for apache2
        regexp: '^DocumentRoot.*$'
        replace: 'DocumentRoot "/opt/www"'
        backup: yes
      notify: "restart webserver" 
