- hosts: slave1
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
  - name: Install_apache2
    apt:
      name: apache2
      state: latest
    notify: 
    - enable_apache2
  handlers:
  - name: enable_apache2
    service: 
      name: apache2
      enabled: yes
      state: restarted
